In [1]:
'''Libreria para manipular los datos'''
import pandas as pd

In [2]:
'''cargar el dataset y separarlo por espacio'''
df=pd.read_csv("data_act_01.csv", sep=';')
'''Mostrar los 5 primeros datos'''
df.head()

,CrimeId,OriginalCrimeTypeName,OffenseDate,CallTime,CallDateTime,Disposition,Address,City,State,AgencyId,Range,AddressType
0,160903280,Assault / Battery,2016-03-30T00:00:00,18:42,2016-03-30T18:42:00,REP,100 Block Of Chilton Av,San Francisco,CA,1,NaN,Premise Address
1,160912272,Homeless Complaint,2016-03-31T00:00:00,15:31,2016-03-31T15:31:00,GOA,2300 Block Of Market St,San Francisco,CA,1,NaN,Premise Address
2,160912590,Susp Info,2016-03-31T00:00:00,16:49,2016-03-31T16:49:00,GOA,2300 Block Of Market St,San Francisco,CA,1,NaN,Premise Address
3,160912801,Report,2016-03-31T00:00:00,17:38,2016-03-31T17:38:00,GOA,500 Block Of 7th St,San Francisco,CA,1,NaN,Premise Address
4,160912811,594,2016-03-31T00:00:00,17:42,2016-03-31T17:42:00,REP,Beale St/bryant St,San Francisco,CA,1,NaN,Intersection

In [3]:
'''Dectectar datos nulos dentro del dataframe'''
df.isnull().sum()

CrimeId                      0
OriginalCrimeTypeName        0
OffenseDate                  0
CallTime                     0
CallDateTime                 0
Disposition                  0
Address                      0
City                       321
State                        3
AgencyId                     0
Range                    10051
AddressType                  0
dtype: int64

In [4]:
'''Suma el conteo de duplicados'''
df.duplicated().sum()

0

In [5]:
'''Elimina la columna Range'''
df= df.drop(columns=['Range'], errors='ignore')
'''Muestra valores sin la columna'''
df

,CrimeId,OriginalCrimeTypeName,OffenseDate,CallTime,CallDateTime,Disposition,Address,City,State,AgencyId,AddressType
0,160903280,Assault / Battery,2016-03-30T00:00:00,18:42,2016-03-30T18:42:00,REP,100 Block Of Chilton Av,San Francisco,CA,1,Premise Address
1,160912272,Homeless Complaint,2016-03-31T00:00:00,15:31,2016-03-31T15:31:00,GOA,2300 Block Of Market St,San Francisco,CA,1,Premise Address
2,160912590,Susp Info,2016-03-31T00:00:00,16:49,2016-03-31T16:49:00,GOA,2300 Block Of Market St,San Francisco,CA,1,Premise Address
3,160912801,Report,2016-03-31T00:00:00,17:38,2016-03-31T17:38:00,GOA,500 Block Of 7th St,San Francisco,CA,1,Premise Address
4,160912811,594,2016-03-31T00:00:00,17:42,2016-03-31T17:42:00,REP,Beale St/bryant St,San Francisco,CA,1,Intersection
...,...,...,...,...,...,...,...,...,...,...,...
10046,160964210,Well Being Check,2016-04-05T00:00:00,23:38,2016-04-05T23:38:00,GOA,Hollister Av/hawes St,San Francisco,CA,1,Intersection
10047,160964216,Traffic Stop,2016-04-05T00:00:00,23:43,2016-04-05T23:43:00,ADV,California St/mason St,San Francisco,CA,1,Intersection
10048,160964227,Traffic Stop,2016-04-05T00:00:00,23:48,2016-04-05T23:48:00,CIT,Rosella Ct/onondaga Av,San Francisco,CA,1,Intersection
10049,160964229,Passing Call,2016-04-05T00:00:00,23:48,2016-04-05T23:48:00,Not recorded,0 Blk Herbst Rd,San Francisco,CA,1,Geo-Override
10050,160964249,Traffic Stop,2016-04-05T00:00:00,23:54,2016-04-05T23:54:00,ADV,Grant Av/geary St,San Francisco,CA,1,Intersection

# Imputación de la columna City

In [6]:
'''Importación de librerías'''
import numpy as np
'''Librería para crear matrices o vectores'''
from sklearn.impute import SimpleImputer
'''Librería para sustituir valores nulos por otros valores '''
from sklearn.impute import KNNImputer
'''Sustituye los valores nulos por otros de la frequencia'''
imputer_mf = SimpleImputer(strategy='most_frequent', missing_values=np.nan)
'''Se entrena los valores de la columna City'''
imputer_mf= imputer_mf.fit(df[['City']])
'''Se transforma los valores por otros a la otra columna'''
df['City']=imputer_mf.transform(df[['City']])
'''Se analiza si el dataset esta limpio '''
df['City'].isnull().sum()
'''Se muestra el dataset'''
df

,CrimeId,OriginalCrimeTypeName,OffenseDate,CallTime,CallDateTime,Disposition,Address,City,State,AgencyId,AddressType
0,160903280,Assault / Battery,2016-03-30T00:00:00,18:42,2016-03-30T18:42:00,REP,100 Block Of Chilton Av,San Francisco,CA,1,Premise Address
1,160912272,Homeless Complaint,2016-03-31T00:00:00,15:31,2016-03-31T15:31:00,GOA,2300 Block Of Market St,San Francisco,CA,1,Premise Address
2,160912590,Susp Info,2016-03-31T00:00:00,16:49,2016-03-31T16:49:00,GOA,2300 Block Of Market St,San Francisco,CA,1,Premise Address
3,160912801,Report,2016-03-31T00:00:00,17:38,2016-03-31T17:38:00,GOA,500 Block Of 7th St,San Francisco,CA,1,Premise Address
4,160912811,594,2016-03-31T00:00:00,17:42,2016-03-31T17:42:00,REP,Beale St/bryant St,San Francisco,CA,1,Intersection
...,...,...,...,...,...,...,...,...,...,...,...
10046,160964210,Well Being Check,2016-04-05T00:00:00,23:38,2016-04-05T23:38:00,GOA,Hollister Av/hawes St,San Francisco,CA,1,Intersection
10047,160964216,Traffic Stop,2016-04-05T00:00:00,23:43,2016-04-05T23:43:00,ADV,California St/mason St,San Francisco,CA,1,Intersection
10048,160964227,Traffic Stop,2016-04-05T00:00:00,23:48,2016-04-05T23:48:00,CIT,Rosella Ct/onondaga Av,San Francisco,CA,1,Intersection
10049,160964229,Passing Call,2016-04-05T00:00:00,23:48,2016-04-05T23:48:00,Not recorded,0 Blk Herbst Rd,San Francisco,CA,1,Geo-Override
10050,160964249,Traffic Stop,2016-04-05T00:00:00,23:54,2016-04-05T23:54:00,ADV,Grant Av/geary St,San Francisco,CA,1,Intersection

# Valores duplicados

In [7]:
'''Mostrar los valores duplicado columna OffenseDate'''
df.OffenseDate.duplicated().sum()

10042

In [8]:
'''Mostrar los valores duplicado columna OffenseDate'''
df.CallDateTime.duplicated().sum()

4935